// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0424LU5WZv_lVY27YHhAQOxX-59j3I_w',
    appId: '1:232015512903:web:7f827aaef75b679b4e7862',
    messagingSenderId: '232015512903',
    projectId: 'gonomad-28aaa',
    authDomain: 'gonomad-28aaa.firebaseapp.com',
    databaseURL: 'https://gonomad-28aaa-default-rtdb.firebaseio.com',
    storageBucket: 'gonomad-28aaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADcl8BPZdWFe4TmVT0ZJZ8nuqKEJkkGs4',
    appId: '1:232015512903:android:8dea19b7c844263a4e7862',
    messagingSenderId: '232015512903',
    projectId: 'gonomad-28aaa',
    databaseURL: 'https://gonomad-28aaa-default-rtdb.firebaseio.com',
    storageBucket: 'gonomad-28aaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZXrCVa4Q1J2FVh_qiCr4yWxjaA40mmMk',
    appId: '1:232015512903:ios:7a8ef00a2013161e4e7862',
    messagingSenderId: '232015512903',
    projectId: 'gonomad-28aaa',
    databaseURL: 'https://gonomad-28aaa-default-rtdb.firebaseio.com',
    storageBucket: 'gonomad-28aaa.appspot.com',
    androidClientId: '232015512903-ang68fs8rn5b3kmi5oskjsd2eprkho7l.apps.googleusercontent.com',
    iosClientId: '232015512903-b2b6shbcl8otg568nmgik1vciaaoifll.apps.googleusercontent.com',
    iosBundleId: 'com.example.gonomad',
  );
}
